### ISSUE TITLE
Schemas node in the generated file is always empty

### ISSUE THREAD

**Issue by elidrissidev** [marcelthole/openapi-merge#32]
I ran this tool to merge the OpenAPI files from this repository: https://github.com/UPS-API/api-documentation like so:

```sh
vendor/bin/openapi-merge Shipping.json OAuth\ ClientCredentials.json Tracking.json -o open-api.json
```

but the `components.schemas` object in the generated file is always empty.

**Comment by marcelthole** [comment]
Hey,
thanks for the bug report. I could reproduce it locally and will take a deeper look

**Comment by marcelthole** [comment]
I released a fix that will solve the Problem if you use `--resolve-references=0`
Without that argument the resolve-references is activated by default and the open-api.json should not contain any `$refs` anymore and therefore no components.schema are required anymore

**Comment by elidrissidev** [comment]
@marcelthole Thanks a ton for the swift fix!
